### PR TITLE
feat: Adds Schedule Timeline and Cards

### PR DESCRIPTION
**Pull request by ekwoka**
This will need models added to the main builder account for the talk data themselves, but otherwise I think this works quite nicely.

Can adjust styles as needed, add more card types, etc.

### CODE REVIEW

**Comment by wiktoriavh** [comment]
Components should have their own directory, this directory contains the component and tests, optionally also styles. A directory can contain more than one component, if they fit together.

For example `navigation` contains Header and Footer.

**Comment by ekwoka** [comment]
That seems inefficient.

Should they then have a barrel or no? Do we need to import every component separately or will they be barrelled in a higher level? Shouldn't a css module be not advised since the project uses tailwind?

What about layout and atomic components?

Should header and footer even be navigation? 

Wouldn't the different navigation components inside those be the navigation components? Then would the header and footer even be navigation anymore?

I've got a lot of questions about this structure. 🤔

**Comment by wiktoriavh** [comment]
> Should they then have a barrel or no?

There can be a barrel file in that directory.

> Shouldn't a css module be not advised since the project uses tailwind?

It depends on the use case of that css module. If there is a good reason to use it, I am fine with it. But overall, Tailwind over CSS Module.

> What about layout and atomic components?

The `components` directory has directory of the individual Components, not directories for atomic structures.

> Should header and footer even be navigation?

In my opinion, they are part of the navigation, since that's where you will find the links to either navigate the site, or navigate to another site.

This is not a complex website that requires hundreds of components, also having one directory with several different components, makes little sense to me.

**Comment by wiktoriavh** [comment]
I have changed my opinion on one thing, which i will fix in another branch.

Components should be in their own directory contain, the directory being the name of the component.  That directroy than contains the component, test, types and consts. and the barrel file, of course.

```
/Header
  - Header.tsx
  - Header.test.tsx
  - Header.modules.css
  - const.ts
  - type.ts
  - index.ts
```

Here is an example. Most files are not needed of course. Types and const(ants) can be inside of the component file itsel, but if they are being exported, they should be in their own file (types or const). the barrel file exports everything; component, const, type.

I will update the contribution page about it as well.

**Comment by ekwoka** [comment]
Pushed a bunch of changes, had some issues where I though I was up to date, but actually wasn't and remade the talk card but also you made a talk card and blah....

ugh, looks like a big conflict when it merged the `TalkCard` files without giving me a conflict warning...will resolve...

**Pull request closed without merging**
